### ISSUE TITLE
🐛 [Tandoor] System page not opening

### ISSUE THREAD

**Issue by Wiz0r** [runtipi/runtipi-appstore#3003] opened 2024-03-31 08:08 UTC
### Store Application

Tandoor

### App version

1.5.15

### Description

The „System“ page is opening with an error

### Steps to reproduce

1. Open Menu
2. Open User Menu
3. Click on System

### App logs

```bash
TypeError at /system/
'>=' not supported between instances of 'tuple' and 'int'
Request Method:	GET
Request URL:	https://xyz.de/system/
Django Version:	4.2.11
Exception Type:	TypeError
Exception Value:	
'>=' not supported between instances of 'tuple' and 'int'
Exception Location:	/opt/recipes/cookbook/views/views.py, line 300, in system
Raised during:	cookbook.views.views.system
Python Executable:	/opt/recipes/venv/bin/python
Python Version:	3.12.2
Python Path:	
['/opt/recipes',
 '/opt/recipes/venv/bin',
 '/usr/local/lib/python312.zip',
 '/usr/local/lib/python3.12',
 '/usr/local/lib/python3.12/lib-dynload',
 '/opt/recipes/venv/lib/python3.12/site-packages']
Server time:	Sun, 31 Mar 2024 10:02:56 +0200
```

### Browser

Brave, Chrome

### Please confirm the following

- [X] I believe this issue is a bug that affects all users of RunTipi, not something specific to my installation.
- [X] I have already searched for relevant existing issues and discussions before opening this report.
- [X] I have updated the title field above with a concise description.

**Comment by Wiz0r** [comment] 2024-04-01 07:47
Seems to be a Tandoor bug:
https://github.com/TandoorRecipes/recipes/issues/3053

**Comment by meienberger** [comment] 2024-04-01 14:54
Closing as this is not a bug related to runtipi

**Closed** 2024-04-01 14:54 UTC
Labels: bug

**Comment by BobWs** [comment] 2024-04-02 07:38
I'm having the same problem after updating my container to the latest versions yesterday! Will this be fix in the next release? Or should I downgrade to a previous version for the timebeing?

**Comment by Wiz0r** [comment] 2024-04-02 07:54
The Tandoor developers know the bug. I would assume that they fix will be deployed with the next Version.
