### ISSUE TITLE
🐛 [MyApp] Concise description of the issue

### ISSUE THREAD

**Issue by n0w33d** [runtipi/runtipi-appstore#3502] opened 2024-05-18 05:18 UTC
### Store Application

Cloudflared

### App version

latest

### Description

After installing and running Cloudflared, its web UI is not accessible and provides an "ERROR_CONNECTION_REFUSED" error in browser. 

The logfile states that a config.json is not created or locatable. The webUI fails to start or accept an http handshake. The user must manually input the Cloudflared service install token via docker CLI.

**Screenshots**
Cloudflared inaccessible:
![image](https://github.com/runtipi/runtipi/assets/106119998/8da37d84-34ee-4a27-8934-a51430af5d5f)

### Steps to reproduce

1. Go to tipi App Store
2. Search & install Cloudflared
3. Launch application.
4. See error.

### App logs

```bash
Docker Desktop log:

sh: 1: cd: can't cd to /data/apps/cloudflared
cloudflared  | WebUI running on port 14333
cloudflared  | No pre-existing config file found.
```
```


### Browser

Edge, Safari

### Browser logs

_No response_

### User-Config changes

_No response_

### Other

- OS: Windows 11 Pro, 23H2, build 22631.3593
- OS running tipi: Windows Subsystem for Linux (WSL2), Debian GNU/Linux 12 (bookworm)
- Tipi Version: v3.2.0

### Please confirm the following

- [X] I believe this issue is a bug that affects all users of RunTipi, not something specific to my installation.
- [X] I have already searched for relevant existing issues and discussions before opening this report.
- [X] I have updated the title field above with a concise description.

**Comment by Lancelot-Enguerrand** [comment] 2024-12-14 11:58
Hello @n0w33d,

As far as my tests goes, on different setups, the cloudflared WebUI is accessible as intended. ✅
This may have been an old bug.

Is this still a issue for you ?

**Comment by Lancelot-Enguerrand** [comment] 2024-12-22 20:56
Thank you for this update, marking it as resolved.

**Closed by Lancelot-Enguerrand** 2024-12-22 20:56 UTC
Labels: bug
